### PR TITLE
feat: inline video (and their poster image attribute)

### PR DESCRIPTION
**Pull request by hsablonniere**
It sounds crazy but for videos with a "reasonable length", it works just fine.

I handle the `src` and `poster` attribute.

### CODE REVIEW

**Comment by remy** [comment]
This is good, but I *think* that videos should be opt-in to inlining - and should be included in the CLI help as an option. What do you think?

**Comment by hsablonniere** [comment]
I agree. I'll update the PR and also fix the CLI params bugs...

**Comment by remy** [comment]
Did this get updated in the end?

**Comment by hsablonniere** [comment]
I've just came back from holidays. I'll work on it soon.

**Comment by remy** [comment]
np, just checking in :)

**Comment by hsablonniere** [comment]
Since my last PR, there was some refactoring so I'm trying something new.

Should I handle `poster` attribute as images and only video `src` in the video option?

**Comment by remy** [comment]
Not sure I follow...

**Comment by hsablonniere** [comment]
Video tag `poster` attributes are just simple images. I'm wondering if the opt-in for videos also applies to their poster or if a video `poster` attribute is handled as an image `src` attribute.

**Comment by hsablonniere** [comment]
I updated the code :
* rebased on new master
* video support with poster image
* video inlining is disabled by default

;-)

**Pull request merged**
