### PR TITLE
feat: support for only inlining local files

### PR DESCRIPTION
**Pull request by eigenuser**
The use case is one where you want to keep CDN hosted libraries external but only inline your own files.

    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/angular-material/1.0.5/angular-material.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/angular-material/1.0.5/angular-material.css" rel="stylesheet">
    
    
    <script src="./app.js"></script>

### CODE REVIEW

**Comment by remy** [comment]
Okay, took me a while to get this PR straight in my head, but rather than `noremote`, I think you want something like `same-origin-only` - so you're using positive language too (rather than "no remote true" - which is harder to parse).

I would also lose the short version, and this might also mean you can do the logic entirely inside of the `lib/get.js` to check the source url vs. the url that we're about to request. Also the URL might not be a different origin just because it starts with `http...`.

If you're happy to make those changes, I'm happy to merge in.

**Comment by eigenuser** [comment]
Hi, thanks for the quick review. I definitely prefer your suggestion for the flag name, and I've already made the change. I was worried earlier about deviating from what seemed like the established patterns in the flag naming (`nocompress`, `noimages`, etc.), but `--same-origin-only` is clearer, and I omitted the corresponding short flag.

I'm open to consolidating the code that enforces this flag into a single spot. However, I'm having trouble figuring out how to accomplish this in `lib/get.js`. The expected return value of `get()` appears to be a promise that resolves with a response-like object with properties for `headers`, `body`, and the like. I haven't thoroughly traced through the promise chaining, but at the moment I'm wondering whether it's too late to try to skip processing an asset once inside `get()`. Perhaps you can provide some helpful pointers; I'm willing to bet I'm missing something obvious. Thanks!

**Comment by eigenuser** [comment]
Gentle bump.

**Comment by remy** [comment]
Sorry, I thought it was going to be consolidated. I'll try to find some time to pull this branch to do the work, I've been looking at it in detail, and I appreciate it's not setup to do it, but I think it's the right change.

**Comment by remy** [comment]
I've been looking at this again, I don't think there's a way to route the change entirely through `lib/get.js`.

However, I'm also worried this test would fail this kind of HTML (when served over http://localhost:12345) - it would incorrectly skip the image (because the origin test doesn't actually test the origin, but just whether it's a relative path):

```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>External image (or local but already resolved source URL)</title>
</head>
<body>
  <img src="http://localhost:54321/1x1.gif">
</body>
</html>
```

**Comment by eigenuser** [comment]
I suppose once the feature gets characterized as "only include resources from the same origin only", some room for confusion gets introduced. To qualify as the same origin, the URI for the resource really ought to match the hostname and port (and scheme, technically) — so we'd have to parse the resource URI as the URI of the "current request" and then make sure these URI components match. I'm not sure whether there's a URL parser built into Node; if not, I suppose we'd have to include an additional package.

In addition, this comparison of URI components, of course, raises a small issue in the command-line usage; there is no "current request" so you'd have to pass in a command-line argument specifying what the canonical scheme+hostname+port should be for comparison purposes.

Anyway, the above considerations were things I was deliberately ignoring, to be honest. I fully admit that I was attempting to do something expedient & lightweight and that I was focused on the command-line usage (thus my original choice of language describing resources as being local or remote — versus being from same or different origins). I appreciate that using fully-qualified URIs (ignoring scheme) is an imprecise indicator of whether an embedded resource is hosted on the same origin as the referencing resource; however, I do know that a URI **without** the hostname MUST be on the same origin. (It occurs to me now that therein lies one advantage of referring to the flag as `noremote` or else `noexternal` or even `exclude-fully-qualified`; it kind of implies that I'm culling external resources without guaranteeing that I'm only including internal ones.)

Let me know which path forward you prefer to follow, and I'll happily follow your lead. Thanks!

**Comment by eigenuser** [comment]
Any further thoughts? To reiterate, I'm hoping to avoid sliding toward complexity and only target resources with absolute URLs. Casting the feature as "same origin only" is perhaps the source of discomfort here; a flag name of `--skip-absolute-urls` would perhaps clear up the true intent.

**Comment by remy** [comment]
I think moving to `--skip-absolute-urls` makes the most sense and it reflects what you're trying to do here.

**Comment by eigenuser** [comment]
Cool, thanks!

**Comment by eigenuser** [comment]
@remy ping.

**Comment by remy** [comment]
I was actually merging yesterday but work got the better of me. I'm merging up now (with recent changes to master). Look out for a new release shortly.

**Pull request merged**
