### PR TITLE
feat: added preserveComments option

### PR DESCRIPTION
**Pull request by reimertz**

### CODE REVIEW

**Comment by reimertz** [comment]
Hey @remy, what do you think about this?

**Comment by remy** [comment]
All good. I want to merge with another pr and fix though, if you don't mind waiting a little longer.

**Comment by reimertz** [comment]
@remy no worries at all. :)

**Comment by reimertz** [comment]
@remy don't want to be that guy, but it's new years eve soon and I have been looking forward to celebrating this PR getting merged..
< <
> >

**JK**, happy new years eve and when you have the time, please merge. 🎉🎉

**Comment by remy** [comment]
This is merged and live in inliner@1.10.0 (though I've removed the `-c` shortcut in 1.10.1 and added the option to the help output).

4:30pm on NYE - hopefully that still works for you 😄 🎉

**Comment by remy** [comment]
It didn't auto close this PR, but here's the commit: https://github.com/remy/inliner/commit/a41ab78a95bef648695251f71e89e95ed54842f1

**Comment by reimertz** [comment]
F*ck yeah! 

We can both now forget all the shit that happened this year, because we can always think about this moment and how this PR was merged into master. 

Happy NYE! 🎉🦄🌠

**Pull request closed without merging**
