### PR TITLE
Fixed SVG base64 encoded references in the css to be wrapped in singl…

### PR DESCRIPTION
**Pull request by cecotw**
…e quotes.

### CODE REVIEW

**Comment by remy** [comment]
I can't merge this at the moment, it's failing tests (and doesn't include tests itself). The commit message also needs rebasing (which I can help with if you need).

I assume this is related to #96. If so, can you at least provide a working demo of the inliner failing - the directions [here](https://github.com/remy/inliner/blob/master/CONTRIBUTING.md#contributing) should help guide you.

Thanks so much for the PR and I'll help as much as I can to get it merged in.

**Comment by cecotw** [comment]
Hey Remy,
This is the same issue as #96. I wasn't able to create a pull request on that ticket so I created a new one. Here is an example of a base 64 encoded CSS background property generated with inliner: http://codepen.io/anon/pen/QNRjvN

Notice how the background base64 encoded SVG does not display. Here is a fork of the same code, only this time the background CSS URI is wrapped in single quotes: http://codepen.io/anon/pen/vGwNZP

The background image for this displays now. I think it has something to do with the encoding of the URIs, but I am not too familiar with why the single quotes are necessary (something not getting escaped properly perhaps?). 

We are using this module for an internal tool, so any help in getting this fixed would be greatly appreciated.

Cheers!
Tim

**Comment by remy** [comment]
Hey there, 

I'm trying to pick up outstanding issues on this repo today, but the codepens you sent me to, I don't know how to get the full (unencumbered) output (I'm also the author of jsbin, so there's not really much reason to learn codepen either 😄). 

Can you put the raw output on a gist for me to try to replicate and merge?

**Comment by remy** [comment]
Actually, I was able to replicate in jsbin https://jsbin.com/vagitel/edit?html,css,output so I now see what's going on.

I'll probably have to create this commit anew only because the commit format is wrong, and it's failing the linting tests.

**Comment by remy** [comment]
Heh. The change wasn't quite as simple as your PR, but it's in now and has tests. Cheers for spotting it.

**Pull request closed without merging**
