### PR TITLE
feat: add iesafe option

### LINKED ISSUE #134: Add option to output IE-safe compressed JS
As it stands inliner can produce output that breaks JS parsing in old IE. Setting `screw_ie8: false` in `minify()` should do the trick.

### PR DESCRIPTION
**Pull request by pinkhominid**
Fixes #134

### CODE REVIEW

**Comment by pinkhominid** [comment]
Please review when you get time and let me know if I should make any tweaks.

**Comment by remy** [comment]
Sorry I let this slip past my radar. If you can make the suggested tweak, then I'm happy to merge.

**Comment by pinkhominid** [comment]
Sorry I may have missed something. Which suggested tweak? :)

**Comment by pinkhominid** [comment]
Strange..for some reason I'm not seeing your review. It should show up in the pull request convo tab but this is all I'm seeing.
screen shot 2017-04-04 at 5 01 11 pm

**Comment by remy** [comment]
That's a bit naff!

Here's the comment: 

Sorry for the super late feedback, but could you rename this (`screwIe8`) variable? Perhaps something like notIESafe?

I appreciate that this maps 1:1 with uglifyjs and not your naming

---

I'm just setting down to sleep, but if you update it, I'll merge it first thing.

**Comment by pinkhominid** [comment]
Great thanks. I'll make the change. Sorry to keep bugging you. Not sure why that comment disappeared. Very odd..

**Pull request merged**
