### PR TITLE
fix wrong url parsing for images

### LINKED ISSUE #72: error when inlining page with bootstrap
hi,

when inlining a page which references bootstrap i always get this error:

    λ inliner -v inliner.html
    0/1
    loading inliner.html
    1/1
    1/2
    processing external css D:\tmp\test\css\bootstrap.css
    loading D:\tmp\test\css\bootstrap.css
    2/2
    compress css
    2/8
    get image D:\tmp\test\fonts\glyphicons-halflings-regular.eot
    loading D:\tmp\test\fonts\glyphicons-halflings-regular.eot
    get image D:\tmp\test\fonts\glyphicons-halflings-regular.eot?
    loading D:\tmp\test\fonts\glyphicons-halflings-regular.eot?
    get image D:\tmp\test\fonts\glyphicons-halflings-regular.woff2
    loading D:\tmp\test\fonts\glyphicons-halflings-regular.woff2
    get image D:\tmp\test\fonts\glyphicons-halflings-regular.woff
    loading D:\tmp\test\fonts\glyphicons-halflings-regular.woff
    get image D:\tmp\test\fonts\glyphicons-halflings-regular.ttf
    loading D:\tmp\test\fonts\glyphicons-halflings-regular.ttf
    get image D:\tmp\test\fonts\glyphicons-halflings-regular.svg
    loading D:\tmp\test\fonts\glyphicons-halflings-regular.svg
    ENOENT: no such file or directory, open 'D:\tmp\test\fonts\glyphicons-halflings-regular.eot?'

it seems like somehow the `?` becomes part of the path.

the used html:

```html
<!DOCTYPE html>
<html>
  <head>
    <title>inliner error</title>
    <link rel="stylesheet" type="text/css" href="bootstrap.css">
  </head>
  <body>
  </body>
</html>
```

bootstrap is v3.3.5.

if you can point me where to have a look i can propose a pr. or if it is in another lib (eg. cheerio) i can create an issue there.

thanks for your help.

### PR DESCRIPTION
**Pull request by dotob**
? was left in url

added tests

closes #72

### CODE REVIEW

**Comment by remy** [comment]
Would you mind extending this PR to fix this issue too? https://github.com/remy/inliner/issues/72 It's tangentally related (it's okay if you'd rather not!)

**Comment by dotob** [comment]
yes the fixed issue is exactly related to this. is it alright how i added it?

**Comment by dotob** [comment]
hi @remy is everything alright with this pr? or can i do anything else?

**Comment by remy** [comment]
Merged and live.

**Pull request closed without merging**
