### PR TITLE
--nocache option

### PR DESCRIPTION
**Pull request by cricri**

### CODE REVIEW

**Comment by remy** [comment]
What's the thinking behind this PR? Is there an existing problem it solves?

**Comment by cricri** [comment]
sure!
I have a use case where some files are built independently of the build chain using inliner. When these files are updated, inliner uses the cache version...

**Comment by remy** [comment]
Idle PR so closing. Sorry, happy to reopen (after a rebase) if it becomes active again. Thank you!

**Comment by MarcusSpecht** [comment]
I stumbled upon the same problem. Files are watched and updated if change happens. Cache is always giving me back the first version.

**Comment by okansahin** [comment]
If you use express try this.

`app.use(function (req, res, next) {
  res.header('Cache-Control', 'private, no-cache, no-store, must-revalidate');
  res.header('Expires', '-1');
  res.header('Pragma', 'no-cache');
  next()
});
`

**Pull request closed without merging**
