### PR TITLE
fix: don't inline background images when the images option is false

### LINKED ISSUE #105: Background images are still embedded with the -i option
For example `background: url('bg.jpg');` still gets inlined even though I have the `-i` option specified. Is this intentional?

### PR DESCRIPTION
**Pull request by cadejscroggins**
This fixes #105 for me. It's probably not how you'd do it, but it's working.

### CODE REVIEW

**Comment by remy** [comment]
Looks good, but can you also include a test to show your fix in action? (There's directions on how to in the contributing doc).

Thanks so much.

**Comment by cadejscroggins** [comment]
Donezo.

**Comment by cadejscroggins** [comment]
@remy bump 🙃

**Comment by remy** [comment]
Not sure why this didn't auto close, but it's live in 1.9.3: https://github.com/remy/inliner/commit/701bf136786b6812e995337a6b7a56eae79fe327

**Pull request closed without merging**
